name: Sync dev database

on:
  push:
    branches:
      - dev
    paths:
      - 'prisma/schema.prisma'
  pull_request:
    branches:
      - dev
    paths:
      - 'prisma/schema.prisma'

jobs:
  migration:
    name: Sync schema change to dev database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Deploy migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
        run: npx prisma migrate deploy
