name: Sync prod database

on:
  push:
    branches:
      - main
    paths:
      - 'packages/db/prisma/schema.prisma'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/db/prisma/schema.prisma'

jobs:
  migration:
    name: Sync schema change to prod database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Deploy migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
        run: yarn workspace @umamin/db prisma migrate deploy
